name: pchange
channels:
   - conda-forge
   - ncar
dependencies:
   - python=3.6
   - poppler=0.52
   - xerces-c=3.1
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - metpy
   - siphon
   - pynio=dev
   - xarray
   - scipy
   - boto
