name: pchange
channels:
   - conda-forge
   - ncar
dependencies:
   - python=3.6
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - metpy
   - siphon
   - pynio
   - xarray
   - scipy
   - boto
   - coincbc=2.9.9
   - pip:
     - git+https://github.com/jjhelmus/CyLP.git@py3
     - git+https://github.com/ARM-DOE/pyart
     - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git

